#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════
   Design Token Forge — Static Build

   Generates static JSON files from CSS tokens for GitHub Pages
   deployment. The Figma plugin polls these files for changes.

   Usage:
     node build-static.js [--out-dir ./dist]

   Output:
     dist/status.json  — lightweight hash check (plugin polls this)
     dist/tokens.json  — full Figma-compatible variable payload
   ═══════════════════════════════════════════════════════════════ */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import crypto from 'crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

// ── CLI args ──────────────────────────────────────────────────

const args   = process.argv.slice(2);
const outIdx = args.indexOf('--out-dir');
const BASE_OUT_DIR = outIdx !== -1 ? path.resolve(args[outIdx + 1]) : path.resolve(__dirname, '../../dist');

const projIdx = args.indexOf('--project');
const PROJECT_ID = projIdx !== -1 ? args[projIdx + 1] : null;

// If --project is specified, output into dist/{projectId}/
const OUT_DIR = PROJECT_ID ? path.join(BASE_OUT_DIR, PROJECT_ID) : BASE_OUT_DIR;

// ── Import the server's runExport by re-using its module ──────
//    We dynamically import the server module and call runExport.
//    But since runExport isn't exported, we inline the import of
//    just the build functions. Simplest: require the whole server
//    as a build library by extracting runExport into a shared file.
//
//    For now, we use a clean approach: fork the export logic
//    by importing the server.js module path and extracting config.
//    Actually, the cleanest way is to just call the server's
//    /tokens endpoint — but that requires the server running.
//
//    Best approach: make server.js export its runExport function
//    and import it here.

// We'll import from the server module (ESM)
const serverPath = path.join(__dirname, 'server.js');

// We'll conditionally import the config→tokens generator
const generatorPath = path.join(__dirname, 'generate-from-config.js');

// ── Recursive directory copy ──────────────────────────────────
var SKIP_PATTERNS = /\.(bak|old|prev|orig)$|^_TEMPLATE\.html$|^_strip-nav\.js$|\.DS_Store$/;

function copyDirSync(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (SKIP_PATTERNS.test(entry.name)) continue;
    const s = path.join(src, entry.name);
    const d = path.join(dst, entry.name);
    if (entry.isDirectory()) copyDirSync(s, d);
    else fs.copyFileSync(s, d);
  }
}

// ── Convert token overrides to CSS file content ──────────────
function tokensToCSSFile(tokens, title) {
  const ts = new Date().toISOString();
  const lines = [
    `/* ════════════════════════════════════════════════════════════════`,
    `   Design Token Forge — ${title}`,
    `   Generated by build-static.js  ${ts}`,
    `   DO NOT EDIT — regenerated automatically from project config.`,
    `   ════════════════════════════════════════════════════════════════ */`,
    '',
    ':root {'
  ];
  if (tokens.light) {
    for (const [name, val] of Object.entries(tokens.light)) {
      const src = tokens.paletteSrc?.[name] ? ` /* src: ${tokens.paletteSrc[name]} */` : '';
      lines.push(`  --${name}: ${val};${src}`);
    }
  }
  lines.push('}', '', '[data-theme="dark"] {');
  if (tokens.dark) {
    for (const [name, val] of Object.entries(tokens.dark)) {
      lines.push(`  --${name}: ${val};`);
    }
  }
  lines.push('}', '');
  return lines.join('\n');
}

async function main() {
  // Dynamically import server module to access runExport
  // First, we need to modify server.js to export runExport.
  // For the static build, we inline the necessary code instead.

  // Actually, the simplest approach: just run the server's export
  // logic by reading the same CSS files and producing the same output.
  // We achieve this by importing a shared build module.

  // For now: call the server's HTTP endpoint if running,
  // or inline the build. Let's do the inline approach since
  // this is a CI script that won't have the server running.

  console.log('');
  console.log('  Design Token Forge — Static Build');
  console.log('  ─────────────────────────────────');

  // ── Load & validate project config (if --project specified) ──
  const ROOT = path.resolve(__dirname, '../..');
  let projectConfig = null;
  if (PROJECT_ID) {
    const configPath = path.join(ROOT, 'projects', PROJECT_ID, 'config.json');
    if (!fs.existsSync(configPath)) {
      console.error(`  ✗ Project config not found: ${configPath}`);
      process.exit(1);
    }
    projectConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    console.log(`  Project: ${projectConfig.name} (${projectConfig.id})`);
  }

  // Import the build functions from server.js
  // We need to make server.js export them. Let's do that.
  let serverModule;
  try {
    serverModule = await import(serverPath);
  } catch (e) {
    console.error('  ✗ Failed to import server.js:', e.message);
    process.exit(1);
  }

  if (typeof serverModule.runExport !== 'function') {
    console.error('  ✗ server.js does not export runExport(). Please update it.');
    process.exit(1);
  }

  // ── Generate token overrides from config.json ────────────────
  //    If the project has editor-saved CSS at projects/{id}/*.css,
  //    that is the SOURCE OF TRUTH (the editor's per-role AA-fix
  //    walks fill steps and derives on-component independently for
  //    every role — config.json's per-property semanticMap cannot
  //    express that). Parse those files first; only fall back to
  //    config-derived values for files that don't exist yet.
  //
  //    Round-trip rule: editor writes projects/{id}/*.css; build
  //    reads them; build writes dist/projects/{id}/*.css (deploy
  //    mirror only). Source files are never overwritten by build
  //    — doing so silently destroyed editor saves (e.g. Pearl
  //    brand-component-bg-default was #C737D9 in source but the
  //    build replaced it with config's step-500 #DE5AE7).
  let exportOpts = {};
  const projCSSDir = PROJECT_ID ? path.join(ROOT, 'projects', PROJECT_ID) : null;
  const editorTruth = { primitive: false, semantic: false, surface: false };

  // Baseline primitives (spacing, font, radius, etc.) live in the
  // shared CSS file. The editor only saves COLOR primitives per
  // project, so we always merge: baseline first, editor wins for
  // overlapping keys. Without this merge the parsed editor file
  // alone has no spacing/font tokens and every component size token
  // falls back to a literal number (button heights etc.).
  let baselinePrimitives = { light: {}, dark: {} };
  if (serverModule.parseCSSTokens) {
    const TOKENS_DIR = path.join(ROOT, 'packages', 'tokens', 'src');
    try {
      baselinePrimitives = serverModule.parseCSSTokens(path.join(TOKENS_DIR, 'primitives.css'));
    } catch (e) { /* missing baseline → keep empty */ }
  }

  if (PROJECT_ID && serverModule.parseCSSTokens) {
    const tryParse = (file, key, label, merge) => {
      const p = path.join(projCSSDir, file);
      if (!fs.existsSync(p)) return;
      try {
        const parsed = serverModule.parseCSSTokens(p);
        const has = (parsed && (Object.keys(parsed.light || {}).length || Object.keys(parsed.dark || {}).length));
        if (!has) return;
        if (merge) {
          exportOpts[key] = {
            light: { ...(merge.light || {}), ...(parsed.light || {}) },
            dark:  { ...(merge.dark  || {}), ...(parsed.dark  || {}) },
          };
        } else {
          exportOpts[key] = parsed;
        }
        editorTruth[label] = true;
      } catch (e) {
        console.warn(`  ⚠ Failed to parse projects/${PROJECT_ID}/${file}: ${e.message}`);
      }
    };
    tryParse('primitives.css', 'primitiveTokens', 'primitive', baselinePrimitives);
    tryParse('semantic.css',   'semanticTokens',  'semantic',  null);
    tryParse('surfaces.css',   'surfaceTokens',   'surface',   null);
    const truthParts = Object.entries(editorTruth).filter(function (e) { return e[1]; }).map(function (e) { return e[0]; });
    if (truthParts.length) console.log(`  ✓ Editor truth   → ${truthParts.join(', ')} (parsed from projects/${PROJECT_ID}/)`);
  }
  if (projectConfig?.paletteKeys) {
    try {
      const { generateTokenOverrides } = await import(generatorPath);

      const overrides = generateTokenOverrides(projectConfig, baselinePrimitives);
      if (overrides.primitiveTokens && !editorTruth.primitive) exportOpts.primitiveTokens = overrides.primitiveTokens;
      if (overrides.semanticTokens  && !editorTruth.semantic)  exportOpts.semanticTokens  = overrides.semanticTokens;
      if (overrides.surfaceTokens   && !editorTruth.surface)   exportOpts.surfaceTokens   = overrides.surfaceTokens;

      // ── Typography overlay (always-on) ───────────────────────────────
      // Editor truth only covers colour primitives today; typography
      // primitives (font-*, line-*, letter-*) live in the project's
      // typographyConfig and must be overlaid onto whatever primitive
      // base we ended up with — editor truth OR config-generated.
      // Without this, projects with editor-saved primitives.css ship
      // zero typography tokens to Figma even when the designer picked
      // a preset in onboard. Safe to overlay unconditionally because
      // typography keys never collide with prim-* colour keys.
      if (editorTruth.primitive && overrides.primitiveTokens) {
        const typoRe = /^(font-|line-|letter-)/;
        const baseLight = exportOpts.primitiveTokens.light || {};
        const baseDark  = exportOpts.primitiveTokens.dark  || {};
        for (const k of Object.keys(overrides.primitiveTokens.light || {})) {
          if (typoRe.test(k)) baseLight[k] = overrides.primitiveTokens.light[k];
        }
        for (const k of Object.keys(overrides.primitiveTokens.dark || {})) {
          if (typoRe.test(k)) baseDark[k] = overrides.primitiveTokens.dark[k];
        }
        exportOpts.primitiveTokens = { light: baseLight, dark: baseDark };
        const preset = (projectConfig.typographyConfig && projectConfig.typographyConfig.preset) || 'neutral-system (default)';
        console.log(`  ✓ Typography overlay → preset: ${preset}`);
      }

      const parts = [];
      if (overrides.primitiveTokens && !editorTruth.primitive) parts.push('primitives');
      if (overrides.semanticTokens  && !editorTruth.semantic)  parts.push('semantic');
      if (overrides.surfaceTokens   && !editorTruth.surface)   parts.push('surfaces');
      if (parts.length) console.log(`  ✓ Config fallback → ${parts.join(', ')}`);
    } catch (e) {
      console.warn(`  ⚠ Config override generation failed, falling back to CSS: ${e.message}`);
    }
  }

  // ── Load rename map (one-time migration for Figma variable renames) ──
  const renamesPath = path.join(__dirname, 'renames.json');
  if (fs.existsSync(renamesPath)) {
    try {
      const renamesData = JSON.parse(fs.readFileSync(renamesPath, 'utf-8'));
      if (renamesData.renames && Object.keys(renamesData.renames).length > 0) {
        exportOpts.renames = renamesData.renames;
        console.log(`  ✓ renames.json  → ${Object.keys(renamesData.renames).length} path renames`);
      }
    } catch (e) {
      console.warn(`  ⚠ Failed to load renames.json: ${e.message}`);
    }
  }

  const data = serverModule.runExport(exportOpts);

  // Inject project identity into the payload
  if (projectConfig) {
    data.project = { id: projectConfig.id, name: projectConfig.name };
  }

  // Ensure output dir exists
  fs.mkdirSync(OUT_DIR, { recursive: true });

  // Write tokens.json — full payload
  const tokensPath = path.join(OUT_DIR, 'tokens.json');
  fs.writeFileSync(tokensPath, JSON.stringify(data, null, 2));
  console.log(`  ✓ tokens.json  → ${data.stats.totalVariables} variables (${data.contentHash})`);

  // Read git commit SHA for deploy verification
  let buildCommit = '';
  try { buildCommit = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim(); } catch(e) {}

  // Per-project published version — written by the editor's Publish
  // flow into projects/<id>/config.json.latestVersion. This is what
  // designers see in the editor's Version history dialog and is the
  // only version surface we expose in the plugin hero. Already starts
  // with 'v' (e.g. 'v1.0.10').
  const latestVersion = projectConfig && projectConfig.latestVersion ? projectConfig.latestVersion : null;
  const buildVersion  = latestVersion && latestVersion.version ? latestVersion.version : '';
  const versionLabel  = latestVersion && latestVersion.name    ? latestVersion.name    : '';
  const versionSavedAt = latestVersion && latestVersion.savedAt ? latestVersion.savedAt : '';

  // Write status.json — lightweight polling endpoint
  const status = {
    connected: true,
    hash: data.contentHash,
    lastChanged: data.exported,
    buildVersion: buildVersion,
    versionLabel: versionLabel,
    versionSavedAt: versionSavedAt,
    buildCommit: buildCommit,
    pendingChanges: 0,
    totalVariables: data.stats.totalVariables,
    totalCollections: data.stats.totalCollections,
    lastSyncedHash: '',
    ...(projectConfig && { project: { id: projectConfig.id, name: projectConfig.name } })
  };
  const statusPath = path.join(OUT_DIR, 'status.json');
  fs.writeFileSync(statusPath, JSON.stringify(status, null, 2));
  console.log(`  ✓ status.json  → hash ${data.contentHash}${buildVersion ? ' (' + buildVersion + ')' : ''}`);

  // Root index.html — Launchpad (PAT-gated entry that routes to user's project or onboard)
  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Design Token Forge</title>
<style>
  :root {
    --bg: #ffffff; --fg: #0f172a; --fg-sub: #475569; --fg-faint: #64748b;
    --border: #e2e8f0; --surface: #f8fafc; --brand: #286CE5; --brand-hover: #1e54b8;
    --danger: #dc2626; --success: #16a34a;
  }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#0b0d11; --fg:#f1f5f9; --fg-sub:#cbd5e1; --fg-faint:#94a3b8;
            --border:#1e293b; --surface:#111827; --brand:#5b8def; --brand-hover:#7aa3f3; }
  }
  * { box-sizing: border-box; }
  html, body { margin:0; padding:0; height:100%;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    background: var(--bg); color: var(--fg); -webkit-font-smoothing: antialiased; }
  .lp-wrap { min-height:100%; display:grid; place-items:center; padding:40px 24px; }
  .lp-card { width:100%; max-width:460px; }
  .lp-brand { display:flex; align-items:center; gap:10px; margin-bottom:32px; }
  .lp-logo { width:36px; height:36px; border-radius:8px;
    background: linear-gradient(135deg, var(--brand) 0%, #8b5cf6 100%);
    display:grid; place-items:center; color:#fff; font-weight:800; font-size:18px; }
  .lp-brand-name { font-size:14px; font-weight:700; letter-spacing:-0.01em; }
  .lp-title { font-size:24px; font-weight:800; letter-spacing:-0.02em; margin:0 0 8px; }
  .lp-sub   { font-size:14px; color: var(--fg-sub); line-height:1.5; margin:0 0 24px; }

  .lp-field { margin-bottom:14px; }
  .lp-label { display:flex; justify-content:space-between; align-items:baseline;
    font-size:12px; font-weight:700; color:var(--fg); margin-bottom:6px; }
  .lp-help-link { font-size:11px; font-weight:500; color:var(--brand); text-decoration:none; }
  .lp-help-link:hover { text-decoration:underline; }
  .lp-input { width:100%; padding:10px 12px; border:1px solid var(--border);
    border-radius:6px; background: var(--surface); color: var(--fg); font-size:13px;
    font-family: ui-monospace, "SF Mono", Menlo, monospace; }
  .lp-input:focus { outline:2px solid var(--brand); outline-offset:-1px; border-color:transparent; }
  .lp-btn { width:100%; padding:11px 16px; border-radius:6px; border:none;
    background: var(--brand); color:#fff; font-weight:600; font-size:13px;
    cursor:pointer; transition: background 0.15s; }
  .lp-btn:hover:not(:disabled) { background: var(--brand-hover); }
  .lp-btn:disabled { opacity:0.55; cursor:not-allowed; }
  .lp-status { margin-top:12px; font-size:12px; min-height:18px; }
  .lp-status.err { color: var(--danger); }
  .lp-status.ok  { color: var(--success); }
  .lp-status.loading { color: var(--fg-faint); }
  .lp-foot { margin-top:24px; padding-top:16px; border-top:1px solid var(--border);
    font-size:11px; color: var(--fg-faint); line-height:1.5; }

  /* Project picker */
  .lp-userrow { display:flex; align-items:center; gap:10px; padding:10px 12px;
    background:var(--surface); border:1px solid var(--border); border-radius:6px;
    margin-bottom:16px; font-size:13px; }
  .lp-userrow strong { font-weight:700; }
  .lp-signout { margin-left:auto; background:none; border:none; color:var(--fg-faint);
    font-size:11px; cursor:pointer; padding:2px 6px; border-radius:4px; }
  .lp-signout:hover { color:var(--danger); background:rgba(220,38,38,0.08); }
  .lp-projlist { display:flex; flex-direction:column; gap:6px; margin-bottom:16px;
    max-height:280px; overflow-y:auto; }
  .lp-projitem { display:flex; align-items:center; gap:10px; padding:11px 14px;
    border:1px solid var(--border); border-radius:6px; background:var(--surface);
    cursor:pointer; text-align:left; font-family:inherit; color:var(--fg); width:100%; }
  .lp-projitem:hover { border-color: var(--brand); background: rgba(40,108,229,0.05); }
  .lp-projitem-name { font-weight:600; font-size:13px; }
  .lp-projitem-meta { font-size:11px; color:var(--fg-faint); margin-left:auto; }
  .lp-divider { display:flex; align-items:center; gap:10px; margin:14px 0;
    color:var(--fg-faint); font-size:11px; }
  .lp-divider::before, .lp-divider::after { content:''; flex:1; height:1px; background:var(--border); }
  .lp-btn-secondary { background:transparent; color:var(--brand);
    border:1px solid var(--border); }
  .lp-btn-secondary:hover:not(:disabled) { background:var(--surface); border-color:var(--brand); }

  .lp-spinner { display:inline-block; width:12px; height:12px; border:2px solid currentColor;
    border-top-color:transparent; border-radius:50%; animation:lp-spin 0.7s linear infinite;
    vertical-align:middle; margin-right:6px; }
  @keyframes lp-spin { to { transform: rotate(360deg); } }

  .lp-hidden { display:none !important; }
</style>
</head>
<body>
<div class="lp-wrap">
  <div class="lp-card">
    <div class="lp-brand">
      <div class="lp-logo">DT</div>
      <div class="lp-brand-name">Design Token Forge</div>
    </div>

    <!-- Phase 1: PAT entry -->
    <div id="lp-auth">
      <h1 class="lp-title">Welcome</h1>
      <p class="lp-sub">Connect your GitHub account to access your design token projects. We'll route you straight to your work.</p>

      <div class="lp-field">
        <div class="lp-label">
          <span>GitHub Personal Access Token</span>
          <a class="lp-help-link" href="https://github.com/settings/tokens/new?scopes=repo,workflow&description=Design+Token+Forge" target="_blank" rel="noopener">Create one →</a>
        </div>
        <input id="lp-pat" type="password" class="lp-input" placeholder="ghp_..." autocomplete="off" spellcheck="false">
      </div>

      <button id="lp-connect" class="lp-btn">Connect</button>
      <div id="lp-status" class="lp-status"></div>

      <div class="lp-foot">
        Token needs <strong>repo</strong> + <strong>workflow</strong> scopes. It is stored only in your browser.
      </div>
    </div>

    <!-- Phase 2: Project picker (shown after auth) -->
    <div id="lp-pick" class="lp-hidden">
      <h1 class="lp-title">Choose a project</h1>
      <p class="lp-sub">Pick a project to open, or create a new one.</p>

      <div class="lp-userrow">
        <span>Signed in as <strong id="lp-user"></strong></span>
        <button id="lp-signout" class="lp-signout" type="button">Sign out</button>
      </div>

      <div id="lp-projlist" class="lp-projlist"></div>

      <div class="lp-divider">or</div>

      <button id="lp-new" class="lp-btn lp-btn-secondary" type="button">+ Create new project</button>
      <div id="lp-status2" class="lp-status"></div>
    </div>
  </div>
</div>

<script>
(function() {
  var REPO_OWNER = 'sridhar-ravi-2917';
  var REPO_NAME = 'Design-Token-Forge';
  var GH_API = 'https://api.github.com';
  var FORCE = location.search.indexOf('force') !== -1;  // ?force = always show launchpad

  var $auth = document.getElementById('lp-auth');
  var $pick = document.getElementById('lp-pick');
  var $patInput = document.getElementById('lp-pat');
  var $connect = document.getElementById('lp-connect');
  var $status = document.getElementById('lp-status');
  var $status2 = document.getElementById('lp-status2');
  var $user = document.getElementById('lp-user');
  var $signout = document.getElementById('lp-signout');
  var $list = document.getElementById('lp-projlist');
  var $new = document.getElementById('lp-new');

  function setStatus(el, msg, kind) {
    el.className = 'lp-status' + (kind ? ' ' + kind : '');
    el.innerHTML = msg || '';
  }

  function showAuth() { $auth.classList.remove('lp-hidden'); $pick.classList.add('lp-hidden'); }
  function showPick() { $auth.classList.add('lp-hidden'); $pick.classList.remove('lp-hidden'); }

  function go(path) { location.href = path; }

  /* Fetch projects.json (CDN-cached static file, no auth needed) and filter to user */
  function fetchUserProjects(user) {
    return fetch('projects.json?_cb=' + Date.now(), { cache: 'no-cache' })
      .then(function(r) { return r.ok ? r.json() : []; })
      .then(function(list) {
        if (!Array.isArray(list)) return [];
        var userLower = (user || '').toLowerCase();
        return list.filter(function(p) {
          // Show projects the user owns. Projects with no owner are legacy
          // (only visible to admin / unrestricted) — do NOT default-show them.
          return p.owner && p.owner.toLowerCase() === userLower;
        });
      })
      .catch(function() { return []; });
  }

  /* Source-of-truth: hit the GitHub API directly for the user's projects.
     The static projects.json is CDN-cached and lags ~10 minutes after a
     fresh project is created, so we always try the API first when a PAT
     is available. Falls back to the static file on 401/403/rate-limit. */
  function fetchUserProjectsLive(user, pat) {
    if (!pat) return fetchUserProjects(user);
    var headers = { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github+json' };
    var apiBase = GH_API + '/repos/' + REPO_OWNER + '/' + REPO_NAME;
    return fetch(apiBase + '/contents/projects?ref=main&_cb=' + Date.now(), { headers: headers })
      .then(function(r) { if (!r.ok) throw new Error('list_' + r.status); return r.json(); })
      .then(function(dirs) {
        if (!Array.isArray(dirs)) throw new Error('not-array');
        var dirsOnly = dirs.filter(function(d) { return d.type === 'dir'; });
        if (!dirsOnly.length) return [];
        return Promise.all(dirsOnly.map(function(dir) {
          return fetch(apiBase + '/contents/projects/' + dir.name + '/config.json?ref=main', { headers: headers })
            .then(function(r) { return r.ok ? r.json() : null; })
            .then(function(file) {
              if (!file || !file.content) return null;
              try {
                var cfg = JSON.parse(atob(file.content.replace(/\\n/g, '')));
                return { id: cfg.id || dir.name, name: cfg.name || dir.name,
                         owner: cfg.owner || '', description: cfg.description || '' };
              } catch (e) { return null; }
            })
            .catch(function() { return null; });
        })).then(function(items) {
          var userLower = (user || '').toLowerCase();
          return items.filter(function(p) {
            return p && p.owner && p.owner.toLowerCase() === userLower;
          });
        });
      })
      .catch(function() { return fetchUserProjects(user); });
  }

  function renderProjects(projects) {
    $list.innerHTML = '';
    if (!projects.length) {
      var empty = document.createElement('div');
      empty.style.cssText = 'padding:14px;font-size:12px;color:var(--fg-faint);text-align:center;border:1px dashed var(--border);border-radius:6px';
      empty.textContent = 'No projects yet. Create your first one below.';
      $list.appendChild(empty);
      return;
    }
    projects.forEach(function(p) {
      var btn = document.createElement('button');
      btn.className = 'lp-projitem';
      btn.type = 'button';
      var nm = document.createElement('span');
      nm.className = 'lp-projitem-name';
      nm.textContent = p.name || p.id;
      btn.appendChild(nm);
      if (p.description) {
        var meta = document.createElement('span');
        meta.className = 'lp-projitem-meta';
        meta.textContent = p.id;
        btn.appendChild(meta);
      }
      btn.addEventListener('click', function() {
        localStorage.setItem('dtf-active-project', p.id);
        go('demo/index.html');
      });
      $list.appendChild(btn);
    });
  }

  /* Route: with a valid token + user, decide where to land */
  function routeAuthenticated(user, projects) {
    if (!projects.length) {
      // No projects → onboard wizard
      go('demo/onboard.html');
      return;
    }
    var active = localStorage.getItem('dtf-active-project') || '';
    var match = projects.find(function(p) { return p.id === active; });
    if (match && !FORCE) {
      // Active project still belongs to this user → go straight in
      go('demo/index.html');
      return;
    }
    // Otherwise show picker
    $user.textContent = user;
    renderProjects(projects);
    showPick();
  }

  /* Validate a PAT against /user — returns username or throws */
  function validatePat(pat) {
    return fetch(GH_API + '/user', {
      headers: { 'Authorization': 'Bearer ' + pat, 'Accept': 'application/vnd.github+json' }
    }).then(function(r) {
      if (!r.ok) {
        return r.json().then(function(d) { throw new Error(d.message || 'HTTP ' + r.status); });
      }
      return r.json();
    }).then(function(u) { return u.login; });
  }

  $connect.addEventListener('click', function() {
    var pat = ($patInput.value || '').trim();
    if (!pat) { setStatus($status, 'Enter a token to continue.', 'err'); return; }
    $connect.disabled = true;
    $connect.innerHTML = '<span class="lp-spinner"></span>Connecting…';
    setStatus($status, '');
    validatePat(pat).then(function(login) {
      localStorage.setItem('dtf-gh-pat', pat);
      localStorage.setItem('dtf-gh-user', login);
      localStorage.setItem('dtf-gh-owner', login);
      setStatus($status, '✓ Connected as ' + login + '. Loading your projects…', 'ok');
      return fetchUserProjectsLive(login, pat).then(function(projects) {
        routeAuthenticated(login, projects);
      });
    }).catch(function(e) {
      setStatus($status, '✗ ' + (e.message || 'Authentication failed'), 'err');
    }).finally(function() {
      $connect.disabled = false;
      $connect.textContent = 'Connect';
    });
  });
  $patInput.addEventListener('keydown', function(e) {
    if (e.key === 'Enter') $connect.click();
  });

  $signout.addEventListener('click', function() {
    localStorage.removeItem('dtf-gh-pat');
    localStorage.removeItem('dtf-gh-user');
    localStorage.removeItem('dtf-gh-owner');
    localStorage.removeItem('dtf-active-project');
    $patInput.value = '';
    setStatus($status, '');
    showAuth();
    setTimeout(function() { $patInput.focus(); }, 50);
  });

  $new.addEventListener('click', function() { go('demo/onboard.html'); });

  /* ── Auto-route on load if already authenticated ── */
  (function init() {
    var pat = localStorage.getItem('dtf-gh-pat') || '';
    var user = localStorage.getItem('dtf-gh-user') || '';
    if (pat && user && !FORCE) {
      // Silent route — no UI flash
      document.body.style.opacity = '0';
      fetchUserProjectsLive(user, pat).then(function(projects) {
        document.body.style.opacity = '1';
        routeAuthenticated(user, projects);
      });
      return;
    }
    if (pat && user && FORCE) {
      // ?force was used — show picker, don't auto-redirect
      $user.textContent = user;
      fetchUserProjectsLive(user, pat).then(function(projects) {
        renderProjects(projects);
        showPick();
      });
      return;
    }
    showAuth();
    setTimeout(function() { $patInput.focus(); }, 100);
  })();
})();
</script>
</body>
</html>`;
  fs.writeFileSync(path.join(OUT_DIR, 'index.html'), indexHtml);
  console.log('  ✓ index.html   → launchpad (PAT-gated routing)');

  // ── Copy demo pages + dependencies ──────────────────────────
  const demoSrc = path.join(ROOT, 'demo');
  const demoDst = path.join(OUT_DIR, 'demo');

  if (fs.existsSync(demoSrc)) {
    copyDirSync(demoSrc, demoDst);
    console.log('  ✓ demo/        → component explorer');

    // Copy packages/ (tokens + components CSS) so ../packages/ refs work
    const pkgSrc = path.join(ROOT, 'packages');
    const pkgDst = path.join(OUT_DIR, 'packages');
    // Only copy what demos need: tokens/src and components/src
    const tokensSrc = path.join(pkgSrc, 'tokens', 'src');
    const tokensDst = path.join(pkgDst, 'tokens', 'src');
    if (fs.existsSync(tokensSrc)) {
      copyDirSync(tokensSrc, tokensDst);
      console.log('  ✓ packages/tokens/src/');
    }

    // Overwrite surface CSS with per-project values from config overrides
    if (exportOpts.surfaceTokens) {
      const surfPath = path.join(tokensDst, 'surfaces.css');
      const surfCSS = tokensToCSSFile(exportOpts.surfaceTokens, 'T2 Surface Context Tokens');
      fs.writeFileSync(surfPath, surfCSS);
      console.log('  ✓ surfaces.css  → per-project overrides from config');
    }
    if (exportOpts.primitiveTokens) {
      const primPath = path.join(tokensDst, 'primitives.css');
      const primCSS = tokensToCSSFile(exportOpts.primitiveTokens, 'T0 Primitive Colors');
      fs.writeFileSync(primPath, primCSS);
    }
    if (exportOpts.semanticTokens) {
      const semPath = path.join(tokensDst, 'semantic.css');
      const semCSS = tokensToCSSFile(exportOpts.semanticTokens, 'T1 Semantic Tokens');
      fs.writeFileSync(semPath, semCSS);
    }
    const compSrc = path.join(pkgSrc, 'components', 'src');
    const compDst = path.join(pkgDst, 'components', 'src');
    if (fs.existsSync(compSrc)) {
      copyDirSync(compSrc, compDst);
      console.log('  ✓ packages/components/src/');
    }
  }

  // ── Backward compatibility: mirror full output to dist root ──
  if (PROJECT_ID) {
    // Copy tokens + status to root
    fs.copyFileSync(path.join(OUT_DIR, 'tokens.json'), path.join(BASE_OUT_DIR, 'tokens.json'));
    fs.copyFileSync(path.join(OUT_DIR, 'status.json'), path.join(BASE_OUT_DIR, 'status.json'));
    fs.copyFileSync(path.join(OUT_DIR, 'index.html'), path.join(BASE_OUT_DIR, 'index.html'));
    // Mirror demo + packages so existing GitHub Pages URLs keep working
    const rootDemo = path.join(BASE_OUT_DIR, 'demo');
    const rootPkg  = path.join(BASE_OUT_DIR, 'packages');
    if (fs.existsSync(path.join(OUT_DIR, 'demo')))     copyDirSync(path.join(OUT_DIR, 'demo'), rootDemo);
    if (fs.existsSync(path.join(OUT_DIR, 'packages'))) copyDirSync(path.join(OUT_DIR, 'packages'), rootPkg);
    console.log(`  ✓ Backward compat → mirrored to dist/ root`);
  }

  // ── Deploy project config.json so demo pages can load it ────
  if (PROJECT_ID && projectConfig) {
    const cfgDst = path.join(OUT_DIR, 'config.json');
    fs.writeFileSync(cfgDst, JSON.stringify(projectConfig, null, 2));
    console.log('  ✓ config.json  → project configuration');
    // Also mirror to dist root for backward compat
    fs.copyFileSync(cfgDst, path.join(BASE_OUT_DIR, 'config.json'));
    // Mirror to dist/projects/{id}/config.json (color-system.html fetches this path)
    const projDistDir = path.join(BASE_OUT_DIR, 'projects', PROJECT_ID);
    fs.mkdirSync(projDistDir, { recursive: true });
    fs.copyFileSync(cfgDst, path.join(projDistDir, 'config.json'));
    console.log('  ✓ projects/' + PROJECT_ID + '/config.json → for demo pages');
  }

  // ── Mirror editor-saved per-project CSS to dist/ ───────────────
  // The deployed demo fetches /projects/{id}/*.css to apply the
  // project's customized brand/role/surface tokens. Source files
  // (projects/{id}/*.css) are written by the editor and are the
  // truth — build NEVER overwrites them. We only copy them verbatim
  // into the dist mirror. When editor truth is missing (first build
  // of a fresh project), we fall back to config-generated CSS so
  // the deploy still ships sensible values.
  if (PROJECT_ID) {
    const projDistCSSDir = path.join(BASE_OUT_DIR, 'projects', PROJECT_ID);
    fs.mkdirSync(projDistCSSDir, { recursive: true });
    const mirror = (name, fallbackTokens, fallbackTitle) => {
      const srcPath = path.join(projCSSDir, name);
      if (fs.existsSync(srcPath)) {
        fs.copyFileSync(srcPath, path.join(projDistCSSDir, name));
        return 'editor';
      }
      if (fallbackTokens) {
        fs.writeFileSync(path.join(projDistCSSDir, name), tokensToCSSFile(fallbackTokens, fallbackTitle));
        return 'config';
      }
      return null;
    };
    const srcOfP = mirror('primitives.css', exportOpts.primitiveTokens, 'T0 Primitive Colors');
    const srcOfS = mirror('semantic.css',   exportOpts.semanticTokens,  'T1 Semantic Tokens');
    const srcOfU = mirror('surfaces.css',   exportOpts.surfaceTokens,   'T2 Surface Context Tokens');

    // ── Typography append (editor truth preserves colour, typography
    //    lives in config) ──────────────────────────────────────────
    // Editor saves only colour primitives. Typography primitives come
    // from typographyConfig + neutral-system fallback. To keep editor
    // truth verbatim AND ship typography to demo pages, we append a
    // pure-typography block to the mirrored primitives.css file after
    // the verbatim copy lands. Idempotent: if the editor ever starts
    // writing font-* tokens we'll just re-overwrite them with the
    // config values (still correct because typographyConfig is the
    // single source of truth for fonts today).
    if (srcOfP === 'editor' && exportOpts.primitiveTokens) {
      const typoRe = /^(font-|line-|letter-)/;
      const lightTypo = {};
      const darkTypo  = {};
      for (const [k, v] of Object.entries(exportOpts.primitiveTokens.light || {})) {
        if (typoRe.test(k)) lightTypo[k] = v;
      }
      for (const [k, v] of Object.entries(exportOpts.primitiveTokens.dark || {})) {
        if (typoRe.test(k)) darkTypo[k] = v;
      }
      // Idempotent: if the verbatim editor file already contains
      // font-family-headline (a typography marker key), assume the
      // typography block is in-file and skip the append. Keeps
      // re-runs and editor-saved-typography (future) clean.
      const mirrorPath = path.join(projDistCSSDir, 'primitives.css');
      const mirrored = fs.readFileSync(mirrorPath, 'utf-8');
      const alreadyHasTypo = /--font-family-headline\s*:/.test(mirrored);
      if (!alreadyHasTypo && (Object.keys(lightTypo).length || Object.keys(darkTypo).length)) {
        const lines = [];
        lines.push('');
        lines.push('/* ── Typography primitives (appended by build-static; sourced from typographyConfig) ── */');
        if (Object.keys(lightTypo).length) {
          lines.push(':root {');
          for (const [k, v] of Object.entries(lightTypo)) lines.push(`  --${k}: ${v};`);
          lines.push('}');
        }
        if (Object.keys(darkTypo).length) {
          lines.push('[data-theme="dark"] {');
          for (const [k, v] of Object.entries(darkTypo)) lines.push(`  --${k}: ${v};`);
          lines.push('}');
        }
        fs.appendFileSync(mirrorPath, lines.join('\n') + '\n');
      }
    }

    const sources = [srcOfP, srcOfS, srcOfU].filter(Boolean);
    if (sources.length) {
      const allEditor = sources.every(s => s === 'editor');
      const tag = allEditor ? 'editor truth' : sources.join('/');
      console.log(`  ✓ dist/projects/${PROJECT_ID}/*.css → ${tag}`);
    }
  }

  // ── Generate projects.json manifest ─────────────────────────
  const projectsDir = path.join(ROOT, 'projects');
  if (fs.existsSync(projectsDir)) {
    const projectList = [];
    for (const entry of fs.readdirSync(projectsDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const cfgPath = path.join(projectsDir, entry.name, 'config.json');
      if (!fs.existsSync(cfgPath)) continue;
      const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf-8'));
      projectList.push({ id: cfg.id, name: cfg.name, owner: cfg.owner || '', description: cfg.description || '' });
    }
    // Local dev manifest used by `pnpm dev` AND deployed to dist/ so the
    // Figma plugin can fetch the project list. Owner usernames are also
    // present in each project's config.json (publicly readable on GitHub
    // Pages), so withholding the aggregated manifest provides no real
    // privacy — and it breaks the plugin's project picker. Keep both.
    fs.writeFileSync(path.join(ROOT, 'projects.json'), JSON.stringify(projectList, null, 2));
    console.log(`  ✓ projects.json (local) → ${projectList.length} project(s)`);

    // Also deploy to dist/ so the Figma plugin (and any external consumer)
    // can fetch it via GitHub Pages.
    if (fs.existsSync(BASE_OUT_DIR)) {
      fs.writeFileSync(path.join(BASE_OUT_DIR, 'projects.json'), JSON.stringify(projectList, null, 2));
      console.log(`  ✓ projects.json (deployed) → dist/projects.json`);
    }

    // ── Clean up stale project directories from dist/ ───────────
    const validIds = new Set(projectList.map(p => p.id));
    const PROTECTED = new Set(['demo', 'packages']);
    for (const entry of fs.readdirSync(BASE_OUT_DIR, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      if (PROTECTED.has(entry.name)) continue;
      // If it looks like a project dir (has tokens.json or config.json inside) but isn't in the list, remove it
      const dirPath = path.join(BASE_OUT_DIR, entry.name);
      const hasTokens = fs.existsSync(path.join(dirPath, 'tokens.json'));
      const hasConfig = fs.existsSync(path.join(dirPath, 'config.json'));
      if ((hasTokens || hasConfig) && !validIds.has(entry.name)) {
        fs.rmSync(dirPath, { recursive: true, force: true });
        console.log(`  ✓ Cleaned stale project dir: dist/${entry.name}`);
      }
    }
  }

  console.log('');
  console.log(`  Output: ${OUT_DIR}`);
  console.log(`  Deploy this folder to GitHub Pages.`);
  console.log('');
}

/* ── Cache-busting pass ───────────────────────────────────────
   Manual `?v=N` query strings on <script src> / <link href> are a
   permanent footgun: every shipped JS/CSS change needs every
   referencing HTML bumped, otherwise browsers serve the cached
   copy forever (the user can hard-refresh the HTML but the cached
   asset still wins on assets cached with long max-age, especially
   inside same-origin iframes that the editor uses).

   This pass walks every HTML file in dist/, finds every relative
   <script src=>, <link href=>, and rewrites the `?v=...` (or
   inserts one) with a short content hash of the actual referenced
   file. Any byte change in the asset flips the hash → URL changes
   → browser always fetches the new file. No more manual bumping. */
function hashFile(absPath) {
  try {
    var buf = fs.readFileSync(absPath);
    return crypto.createHash('sha1').update(buf).digest('hex').slice(0, 10);
  } catch (e) { return null; }
}
function rewriteHtmlCacheBust(htmlPath) {
  var html = fs.readFileSync(htmlPath, 'utf8');
  var dir  = path.dirname(htmlPath);
  // Match  src="...js" | href="...css" | src='...js' | href='...css'
  // Captures: attr, opening quote, path (no quote), existing query, closing quote
  var rx = /(\s(?:src|href))=(["'])([^"'?#]+\.(?:js|css|mjs))(\?[^"']*)?(\2)/gi;
  var changed = 0;
  var out = html.replace(rx, function (m, attr, q1, p, qs, q2) {
    // Only fingerprint relative paths inside dist/
    if (/^(?:https?:)?\/\//.test(p) || p.startsWith('data:')) return m;
    var absRef = path.resolve(dir, p);
    if (!fs.existsSync(absRef)) return m;
    var h = hashFile(absRef);
    if (!h) return m;
    changed++;
    return attr + '=' + q1 + p + '?v=' + h + q2;
  });
  if (changed > 0 && out !== html) {
    fs.writeFileSync(htmlPath, out);
    return changed;
  }
  return 0;
}
function walkHtml(dir) {
  var totalFiles = 0, totalRefs = 0;
  function walk(d) {
    for (var entry of fs.readdirSync(d, { withFileTypes: true })) {
      var p = path.join(d, entry.name);
      if (entry.isDirectory()) {
        // Skip node_modules just in case
        if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
        walk(p);
      } else if (entry.name.endsWith('.html')) {
        var n = rewriteHtmlCacheBust(p);
        if (n > 0) { totalFiles++; totalRefs += n; }
      }
    }
  }
  walk(dir);
  return { totalFiles: totalFiles, totalRefs: totalRefs };
}

main().then(function () {
  // Run only when we actually produced an output tree
  if (!fs.existsSync(BASE_OUT_DIR)) return;
  var stats = walkHtml(BASE_OUT_DIR);
  if (stats.totalFiles > 0) {
    console.log('  ✓ Cache-bust: rewrote ' + stats.totalRefs + ' asset refs across ' + stats.totalFiles + ' HTML files');
  }
}).catch(e => {
  console.error('Build failed:', e);
  process.exit(1);
});
